### ISSUE TITLE
Generation crash on /beta endpoint for commit b2dd0fc3c9af75022b59ee5bec82f6b686f387d7

### ISSUE THREAD

**Issue by christophwille** [microsoftgraph/MSGraph-SDK-Code-Generator#48]
vipr https://graph.microsoft.com/v1.0/$metadata --writer="GraphODataTemplateWriter"

works a-ok

vipr https://graph.microsoft.com/beta/$metadata --writer="GraphODataTemplateWriter"

crashes with (I only kept the last working and the crashing line)

IEntityRequest.cs       subscription    ->              com\microsoft\graph\requests\ISubscriptionRequest.cs
IEntityRequest.cs       identityRiskEvent       ->              com\microsoft\graph\requests\IIdentityRiskEventRequest.cs

Unhandled Exception: System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Vipr.Core.CodeModel.OdcmProjection.FindCapability[T](String term, OdcmObject odcmObject) in D:\home\MSGraph-SDK-Code-Generator\submodules\vipr\src\Core\Vipr.Core\CodeModel\OdcmProjection.cs:line 206
   at Vipr.Core.CodeModel.OdcmProjection.BooleanValueOf(String term, OdcmObject odcmObject) in D:\home\MSGraph-SDK-Code-Generator\submodules\vipr\src\Core\Vipr.Core\CodeModel\OdcmProjection.cs:line 125
   at Vipr.Core.CodeModel.OdcmProjection.Supports(String term, OdcmObject odcmObject) in D:\home\MSGraph-SDK-Code-Generator\submodules\vipr\src\Core\Vipr.Core\CodeModel\OdcmProjection.cs:line 151
   at Vipr.Core.CodeModel.OdcmProjection.SupportsExpand() in D:\home\MSGraph-SDK-Code-Generator\submodules\vipr\src\Core\Vipr.Core\CodeModel\OdcmProjection.cs:line 181
   at Microsoft.Graph.ODataTemplateWriter.Extensions.Features.get_CanExpand() in D:\home\MSGraph-SDK-Code-Generator\src\GraphODataTemplateWriter\Extensions\FeatureExtensions.cs:line 17
   at RuntimeTemplates.IEntityRequest_cs.TransformText() in d:\home\MSGraph-SDK-Code-Generator\Templates\CSharp\Requests\IEntityRequest.cs.tt:line 47
   at Microsoft.Graph.ODataTemplateWriter.TemplateProcessor.TemplateProcessor.<>c__DisplayClass53_0.<PreProcessTemplate>b__2(ITextTemplatingEngineHost host) in D:\home\MSGraph-SDK-Code-Generator\src\GraphODataTemplateWriter\TemplateProcessor\TemplateProcessor.cs:line 306
   at Microsoft.Graph.ODataTemplateWriter.TemplateProcessor.TemplateProcessor.ProcessTemplate(ITemplateInfo templateInfo, OdcmObject odcmObject, String fileName) in D:\home\MSGraph-SDK-Code-Generator\src\GraphODataTemplateWriter\TemplateProcessor\TemplateProcessor.cs:line 333
   at Microsoft.Graph.ODataTemplateWriter.TemplateProcessor.TemplateProcessor.ProcessTemplate(ITemplateInfo templateInfo, OdcmObject odcmObject, String className, String propertyName, String methodName, String propertyType) in D:\home\MSGraph-SDK-Code-Generator\src\GraphODataTemplateWriter\TemplateProcessor\TemplateProcessor.cs:line 313
   at Microsoft.Graph.ODataTemplateWriter.TemplateProcessor.TemplateProcessor.<>c__DisplayClass41_0.<ProcessTypes>b__0(OdcmObject odcmType) in D:\home\MSGraph-SDK-Code-Generator\src\GraphODataTemplateWriter\TemplateProcessor\TemplateProcessor.cs:line 182
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Microsoft.Graph.ODataTemplateWriter.TemplateProcessor.TemplateWriter.<ProcessTemplates>d__20.MoveNext() in D:\home\MSGraph-SDK-Code-Generator\src\GraphODataTemplateWriter\TemplateProcessor\TemplateWriter.cs:line 64
   at Vipr.FileWriter.Write(IEnumerable`1 textFilesToWrite, String outputDirectoryPath) in D:\home\MSGraph-SDK-Code-Generator\submodules\vipr\src\Core\Vipr\FileWriter.cs:line 15
   at Vipr.Bootstrapper.MetadataToClientSource(String edmxString, String outputDirectoryPath) in D:\home\MSGraph-SDK-Code-Generator\submodules\vipr\src\Core\Vipr\Bootstrapper.cs:line 118
   at Vipr.Bootstrapper.Start(String[] args) in D:\home\MSGraph-SDK-Code-Generator\submodules\vipr\src\Core\Vipr\Bootstrapper.cs:line 45
   at Vipr.Program.Main(String[] args) in D:\home\MSGraph-SDK-Code-Generator\submodules\vipr\src\Core\Vipr\Program.cs:line 14

**Comment by shiftylogic** [comment]
This was an issue in the VIPR tool and has been fixed with PR #126.
