### ISSUE TITLE
ItemWithPath fails in latest core (2.0.0)

### ISSUE THREAD

**Issue by juanmarques** [microsoftgraph/MSGraph-SDK-Code-Generator#516]
Hi team,

I have a method where I get DriveItem with path and I'm getting errors from the request when I have the **#** special character.

So if I encode that character it works , please see the following details.

```
if(path.contains("#")) {
 path = path.replace("#","%23");
}
```

Without the Fix
```
GET https://graph.microsoft.com/v1.0/sites/myTest.sharepoint.com,8eb0793b-bd2c-4c55-9f89-c50344d812a6,074d4c88-f1e2-4815-9664-f250b3660685/lists/48aa2e0d-0599-4be3-976d-4296f601ac34/drive/root:/Test/REGULATORY/EUROPE/CTA/BELGIUM/03-%20Prot.%20Amendment,%20#4 (Protocol v.5.0), dd.19-DEC-2018; IB (Debio 1562), v.7.0, dd.21-JAN-2019; IMPD (Debio 1562), dd.30-NOV-2018:
SdkVersion : graph-java/v3.1.0
```

With the Fix
`GET https://graph.microsoft.com/v1.0/sites/myTest.sharepoint.com,8eb0793b-bd2c-4c55-9f89-c50344d812a6,074d4c88-f1e2-4815-9664-f250b3660685/lists/48aa2e0d-0599-4be3-976d-4296f601ac34/drive/root:/Test/REGULATORY/EUROPE/CTA/BELGIUM/03-%20Prot.%20Amendment,%20%234%20(Protocol%20v.5.0),%20dd.19-DEC-2018;%20IB%20(Debio%201562),%20v.7.0,%20dd.21-JAN-2019;%20IMPD%20(Debio%201562),%20dd.30-NOV-2018:`

Error:
```
14 Apr 2021 18:14:11,184 ERROR [OkHttp https://graph.microsoft.com/...] (DefaultLogger.java:119) - Throwable detail: com.microsoft.graph.http.GraphServiceException: Error code: itemNotFound
Error message: The resource could not be found.

GET https://graph.microsoft.com/v1.0/sites/myTest.sharepoint.com,8eb0793b-bd2c-4c55-9f89-c50344d812a6,074d4c88-f1e2-4815-9664-f250b3660685/lists/48aa2e0d-0599-4be3-976d-4296f601ac34/drive/root:/Test/REGULATORY/EUROPE/CTA/BELGIUM/03-%20Prot.%20Amendment,%20#4 (Protocol v.5.0), dd.19-DEC-2018; IB (Debio 1562), v.7.0, dd.21-JAN-2019; IMPD (Debio 1562), dd.30-NOV-2018:
SdkVersion : graph-java/v3.1.0


404 : Not Found
[...]

[Some information was truncated for brevity, enable debug logging for more details]
```
Method:
```
    public DriveItem getDriveItemByPath(String listId, String siteId, String path) throws ExecutionException, InterruptedException {
        return (DriveItem)this.graphClient.sites(siteId).lists(listId).drive().root().itemWithPath(path).buildRequest(new Option[0]).getAsync().get();
    }
``` 
Thank you.
[AB#8986](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8986)

**Comment by baywet** [comment]
Hi @juanmarques,
Thanks for reaching out.
The issue is most likely coming from [here](https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/blob/dev/Templates/templates/Java/requests/BaseEntityRequestBuilder.java.tt#L62)

Out of curiosity, is this an issue that appeared upgrading from 2.X to 3.X of the Java SDK? or can you reproduce the issue with the version of the SDK you were previously on?

**Comment by juanmarques** [comment]
Hi @baywet ,
I wasn't using this method in 2.X so I can't confirm for you.
I can try to reproduce using 2.X , but anyways do you know about others specials characters that might cause some problems?
Thank you.

**Comment by juanmarques** [comment]
Hi @baywet 

I just tested in 2.X and it also happens there please see following error.
```

Apr 15, 2021 12:01:27 PM com.microsoft.graph.logger.DefaultLogger logError
SEVERE: CoreHttpProvider[send] - 207Graph service exception Error code: itemNotFound
Apr 15, 2021 12:01:27 PM com.microsoft.graph.logger.DefaultLogger logError
SEVERE: CoreHttpProvider[send] - 207Error message: The resource could not be found.
Apr 15, 2021 12:01:27 PM com.microsoft.graph.logger.DefaultLogger logError
SEVERE: CoreHttpProvider[send] - 207
Apr 15, 2021 12:01:27 PM com.microsoft.graph.logger.DefaultLogger logError
SEVERE: CoreHttpProvider[send] - 207GET https://graph.microsoft.com/v1.0/sites/8eb0793b-bd2c-4c55-9f89-c50344d812a6/lists/48aa2e0d-0599-4be3-976d-4296f601ac34/drive/root:/Test/REGULATORY/EUROPE/CTA/BELGIUM/03-%20Prot.%20Amendment,%20#4 (Protocol v.5.0), dd.19-DEC-2018; IB (Debio 1562), v.7.0, dd.21-JAN-2019; IMPD (Debio 1562), dd.30-NOV-2018:
Apr 15, 2021 12:01:27 PM com.microsoft.graph.logger.DefaultLogger logError
SEVERE: CoreHttpProvider[send] - 207SdkVersion : graph-java/v2.2.0
Apr 15, 2021 12:01:27 PM com.microsoft.graph.logger.DefaultLogger logError
SEVERE: CoreHttpProvider[send] - 207Authorization : [PII_REDACTED]
Apr 15, 2021 12:01:27 PM com.microsoft.graph.logger.DefaultLogger logError
SEVERE: CoreHttpProvider[send] - 207
Apr 15, 2021 12:01:27 PM com.microsoft.graph.logger.DefaultLogger logError
SEVERE: CoreHttpProvider[send] - 207
Apr 15, 2021 12:01:27 PM com.microsoft.graph.logger.DefaultLogger logError
SEVERE: CoreHttpProvider[send] - 207404 : Not Found
Apr 15, 2021 12:01:27 PM com.microsoft.graph.logger.DefaultLogger logError
SEVERE: CoreHttpProvider[send] - 207[...]
Apr 15, 2021 12:01:27 PM com.microsoft.graph.logger.DefaultLogger logError
SEVERE: CoreHttpProvider[send] - 207
Apr 15, 2021 12:01:27 PM com.microsoft.graph.logger.DefaultLogger logError
SEVERE: CoreHttpProvider[send] - 207[Some information was truncated for brevity, enable debug logging for more details]
Apr 15, 2021 12:01:27 PM com.microsoft.graph.logger.DefaultLogger logError
SEVERE: Throwable detail: com.microsoft.graph.http.GraphServiceException: Error code: itemNotFound
Error message: The resource could not be found.

GET https://graph.microsoft.com/v1.0/sites/8eb0793b-bd2c-4c55-9f89-c50344d812a6/lists/48aa2e0d-0599-4be3-976d-4296f601ac34/drive/root:/Test/REGULATORY/EUROPE/CTA/BELGIUM/03-%20Prot.%20Amendment,%20#4 (Protocol v.5.0), dd.19-DEC-2018; IB (Debio 1562), v.7.0, dd.21-JAN-2019; IMPD (Debio 1562), dd.30-NOV-2018:
SdkVersion : graph-java/v2.2.0
Authorization : [PII_REDACTED]


404 : Not Found
[...]

[Some information was truncated for brevity, enable debug logging for more details]

com.microsoft.graph.http.GraphServiceException: Error code: itemNotFound
Error message: The resource could not be found.

GET https://graph.microsoft.com/v1.0/sites/8eb0793b-bd2c-4c55-9f89-c50344d812a6/lists/48aa2e0d-0599-4be3-976d-4296f601ac34/drive/root:/Test/REGULATORY/EUROPE/CTA/BELGIUM/03-%20Prot.%20Amendment,%20#4 (Protocol v.5.0), dd.19-DEC-2018; IB (Debio 1562), v.7.0, dd.21-JAN-2019; IMPD (Debio 1562), dd.30-NOV-2018:
SdkVersion : graph-java/v2.2.0
Authorization : [PII_REDACTED]


404 : Not Found
[...]

[Some information was truncated for brevity, enable debug logging for more details]

	at com.microsoft.graph.http.GraphServiceException.createFromConnection(GraphServiceException.java:501)
	at com.microsoft.graph.http.CoreHttpProvider.handleErrorResponse(CoreHttpProvider.java:490)
	at com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:410)
	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:207)
	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:187)
	at com.microsoft.graph.http.BaseRequest.send(BaseRequest.java:345)
	at com.microsoft.graph.requests.extensions.DriveItemRequest.get(DriveItemRequest.java:84)
	at com.docshifter.core.graphAPI.integration.Sharepoint.getItemWithPath(Sharepoint.java:536)
	at com.docshifter.core.SPI.SharePointGraphIntegrationTest.testHashPath(SharePointGraphIntegrationTest.java:73)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)


Process finished with exit code 255

```

If I replace the # characters it works...

	folderName = folderName.replace("#","%23");

`15 Apr 2021 12:03:25,003  INFO [main] (SharePointGraphIntegrationTest.java:77) - 03- Prot. Amendment, #4 (Protocol v.5.0), dd.19-DEC-2018; IB (Debio 1562), v.7.0, dd.21-JAN-2019; IMPD (Debio 1562), dd.30-NOV-2018`

Process finished with exit code 0

**Comment by baywet** [comment]
thanks you for taking the time to test this issue with the 2.X version. I'll try to fix this soon.

**Comment by baywet** [comment]
I've just authored #518 and https://github.com/microsoftgraph/msgraph-sdk-java/pull/728 to address the issue. This should be released next week depending on how the review goes.

**Comment by baywet** [comment]
@juanmarques Since both PRs have been merged the fix should be released this week, next one at latest. Thanks for your patience.

**Comment by juanmarques** [comment]
@baywet Thank you very much!

Really appreciate your quickly answer on it!
