### ISSUE TITLE
Generation crash on /beta endpoint for commit 171f42329cc79ab8aba99ede7e382c4e394fdb87

### ISSUE THREAD

**Issue by christophwille** [microsoftgraph/MSGraph-SDK-Code-Generator#89]
https://graph.microsoft.com/beta/$metadata as of today

EntityCollectionReferencesRequest.cs    tasks   ->              com\microsoft\graph\requests\PlanTasksCollectionReferencesRequest.cs
EntityCollectionReferencesRequest.cs    buckets ->              com\microsoft\graph\requests\PlanBucketsCollectionReferencesRequest.cs

Unhandled Exception: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.Graph.ODataTemplateWriter.Extensions.OdcmModelExtensions.GetServiceCollectionNavigationPropertyForPropertyType(OdcmProperty odcmProperty) in D:\Temp\MSGraph-SDK-Code-Generator\src\GraphODataTemplateWriter\Extensions\OdcmModelExtensions.cs:line 143
   at RuntimeTemplates.EntityCollectionReferencesRequest_cs.GetPostAsyncMethodForReferencesRequest(OdcmProperty odcmProperty) in d:\Temp\MSGraph-SDK-Code-Generator\Templates\CSharp\Base\CollectionRequest.Base.template.tt:line 137
   at RuntimeTemplates.EntityCollectionReferencesRequest_cs.TransformText() in d:\Temp\MSGraph-SDK-Code-Generator\Templates\CSharp\Requests\EntityCollectionReferencesRequest.cs.tt:line 20
   at Microsoft.Graph.ODataTemplateWriter.TemplateProcessor.TemplateProcessor.<>c__DisplayClass53_0.<PreProcessTemplate>b__2(ITextTemplatingEngineHost host) in D:\Temp\MSGraph-SDK-Code-Generator\src\GraphODataTemplateWriter\TemplateProcessor\TemplateProcessor.cs:line 307
   at Microsoft.Graph.ODataTemplateWriter.TemplateProcessor.TemplateProcessor.ProcessTemplate(ITemplateInfo templateInfo, OdcmObject odcmObject, String fileName) in D:\Temp\MSGraph-SDK-Code-Generator\src\GraphODataTemplateWriter\TemplateProcessor\TemplateProcessor.cs:line 334
   at Microsoft.Graph.ODataTemplateWriter.TemplateProcessor.TemplateProcessor.ProcessTemplate(ITemplateInfo templateInfo, OdcmObject odcmObject, String className, String propertyName, String methodName, String propertyType) in D:\Temp\MSGraph-SDK-Code-Generator\src\GraphODataTemplateWriter\TemplateProcessor\TemplateProcessor.cs:line 314
   at Microsoft.Graph.ODataTemplateWriter.TemplateProcessor.TemplateProcessor.<>c__DisplayClass42_0.<ProcessProperties>b__1(OdcmProperty odcmProperty) in D:\Temp\MSGraph-SDK-Code-Generator\src\GraphODataTemplateWriter\TemplateProcessor\TemplateProcessor.cs:line 189
   at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Microsoft.Graph.ODataTemplateWriter.TemplateProcessor.TemplateWriter.<ProcessTemplates>d__20.MoveNext() in D:\Temp\MSGraph-SDK-Code-Generator\src\GraphODataTemplateWriter\TemplateProcessor\TemplateWriter.cs:line 64
   at Vipr.FileWriter.Write(IEnumerable`1 textFilesToWrite, String outputDirectoryPath) in D:\Temp\MSGraph-SDK-Code-Generator\submodules\vipr\src\Core\Vipr\FileWriter.cs:line 15
   at Vipr.Bootstrapper.MetadataToClientSource(String edmxString, String outputDirectoryPath) in D:\Temp\MSGraph-SDK-Code-Generator\submodules\vipr\src\Core\Vipr\Bootstrapper.cs:line 118
   at Vipr.Bootstrapper.Start(String[] args) in D:\Temp\MSGraph-SDK-Code-Generator\submodules\vipr\src\Core\Vipr\Bootstrapper.cs:line 45
   at Vipr.Program.Main(String[] args) in D:\Temp\MSGraph-SDK-Code-Generator\submodules\vipr\src\Core\Vipr\Program.cs:line 14

**Comment by MIchaelMainer** [comment]
Thank you for bringing this to our attention. I believe that the Plan entity will be removed in favor of the PlannerPlan entity. If that's the case, then you won't see this error when it is removed. I'm checking on this.

**Comment by MIchaelMainer** [comment]
Yep, those entities will be removed.
